### ISSUE TITLE
when i use "npm run build",error happend!

### ISSUE THREAD

**Issue by jyj545** [moizKachwala/Angular2-express-mongoose-gulp-node-typescript#26]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'deploy' ]
2 info using npm@3.10.8
3 info using node@v6.9.1
4 verbose run-script [ 'predeploy', 'deploy', 'postdeploy' ]
5 info lifecycle angular2-express-mongo@1.0.0~predeploy: angular2-express-mongo@1.0.0
6 silly lifecycle angular2-express-mongo@1.0.0~predeploy: no script for predeploy, continuing
7 info lifecycle angular2-express-mongo@1.0.0~deploy: angular2-express-mongo@1.0.0
8 verbose lifecycle angular2-express-mongo@1.0.0~deploy: unsafe-perm in lifecycle true
9 verbose lifecycle angular2-express-mongo@1.0.0~deploy: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\jyj\Angular2-express-mongoose-gulp-node-typescript-master\node_modules\.bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Common Files\lenovo\easyplussdk\bin;C:\Program Files (x86)\Lenovo\Lenovo Home\;C:\Program Files\nodejs\;C:\Program Files\TortoiseSVN\bin;D:\JDK1.8\bin;D:\androidsdk\platform-tools;D:\androidsdk\tools;C:\Users\jyj\AppData\Roaming\npm;C:\Program Files (x86)\Microsoft VS Code\bin
10 verbose lifecycle angular2-express-mongo@1.0.0~deploy: CWD: C:\Users\jyj\Angular2-express-mongoose-gulp-node-typescript-master
11 silly lifecycle angular2-express-mongo@1.0.0~deploy: Args: [ '/d /s /c',
11 silly lifecycle   'concurrently --kill-others "gulp watch" "node ./dist/server/bin/www"' ]
12 silly lifecycle angular2-express-mongo@1.0.0~deploy: Returned: code: 1  signal: null
13 info lifecycle angular2-express-mongo@1.0.0~deploy: Failed to exec deploy script
14 verbose stack Error: angular2-express-mongo@1.0.0 deploy: `concurrently --kill-others "gulp watch" "node ./dist/server/bin/www"`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid angular2-express-mongo@1.0.0
16 verbose cwd C:\Users\jyj\Angular2-express-mongoose-gulp-node-typescript-master
17 error Windows_NT 6.1.7601
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "deploy"
19 error node v6.9.1
20 error npm  v3.10.8
21 error code ELIFECYCLE
22 error angular2-express-mongo@1.0.0 deploy: `concurrently --kill-others "gulp watch" "node ./dist/server/bin/www"`
22 error Exit status 1
23 error Failed at the angular2-express-mongo@1.0.0 deploy script 'concurrently --kill-others "gulp watch" "node ./dist/server/bin/www"'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the angular2-express-mongo package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     concurrently --kill-others "gulp watch" "node ./dist/server/bin/www"
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs angular2-express-mongo
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls angular2-express-mongo
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by moizKachwala** [comment]
what were your build steps ?
